---
# Darwin (Mac OS X) tasks file for ansible-role-komodo-edit

# -------------
# Install and configure Komodo Edit
# -------------
- name: Darwin | ensure Komodo Edit present
  homebrew_cask: >
    name=komodo-edit
    state=present